apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL21haWZ1amFsYW0vazhzX3ZhZ3JhbnQ=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  creationTimestamp: "2023-10-02T11:08:26Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-2023113455
  namespace: argo-cd
  resourceVersion: "116263"
  uid: f4de9134-9990-43c6-a1d4-61c8b4555539
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: my-private-https-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/argoproj/argocd-example-apps
  password: my-password
  username: my-username
  insecure: "true"
