apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: argo-cd  # Argo CD only listen for application type to the argocd installed namespace(argo-cd in this case).So its constant.
spec:
  destination:
    namespace: helloworld
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: manifests/hello-kubernetes
    repoURL: https://github.com/maifujalam/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - Validate=false
    - CreateNamespace=true
